[credentials]
hajar = "hajar123"
admin = "admin123"

[ksaar_config]
api_base_url = "https://api.ksaar.fr"
api_key_name = "GASAS"
api_key_password = "GASAS2024"
workflow_id = "deb92463-c3a5-4393-a3bf-1dd29a022cfe"

[ksaar_config.app_config]
page_title = "Dashboard GASAS"
page_icon = "📊"
layout = "wide"
initial_sidebar_state = "expanded" 